sylius_grid:
    grids:
        asdoria_admin_pictogram_group:
            driver:
                name: doctrine/orm
                options:
                    class: '%asdoria.model.pictogram_group.class%'
            sorting:
                position: asc
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: translations.name
                position:
                    type: twig
                    label: sylius.ui.position
                    sortable: position
                    path: .
                    options:
                        template: "@AsdoriaSyliusPictogramPlugin/Grid/Field/pictogram_group_position.html.twig"
            actions:
                main:
                    create:
                        type: create
                    update_positions:
                        type: update_pictogram_group_positions
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                    manage:
                        type: pictogram
                        label: asdoria.ui.manage_pictograms
                        icon: cubes
                        options:
                            link:
                                route: asdoria_admin_pictogram_group_pictograms_index
                                parameters:
                                    pictogramGroupId: resource.id
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [ translations.name ]
