sylius_grid:
    templates:
        action:
            pictogram: '@AsdoriaSyliusPictogramPlugin/Grid/Action/pictogram.html.twig'
            update_pictogram_positions: "@AsdoriaSyliusPictogramPlugin/Grid/Action/Pictogram/updatePositions.html.twig"
            update_pictogram_group_positions: "@AsdoriaSyliusPictogramPlugin/Grid/Action/PictogramGroup/updatePositions.html.twig"
