services:
    asdoria.form.type.data_transformer.products_to_pictogram_groups:
        class: Asdoria\SyliusPictogramPlugin\Form\DataTransformer\ProductsToPictogramGroupsTransformer
        arguments:
            - '@asdoria.factory.pictogram'
            - '@sylius.repository.product'
            - '@asdoria.repository.pictogram_group'
