services:
    asdoria.listener.pictograms_upload:
        parent: sylius.listener.images_upload
        autowire: true
        autoconfigure: false
        public: false
        tags:
            - { name: kernel.event_listener, event: asdoria.pictogram.pre_create, method: uploadImage }
            - { name: kernel.event_listener, event: asdoria.pictogram.pre_update, method: uploadImage }
