services:
    asdoria_pictogram.twig_extension.pictogram:
        class: Asdoria\SyliusPictogramPlugin\Twig\PictogramExtension
        arguments:
            $pictogramRepository: '@asdoria.repository.pictogram'
        tags:
            - { name: twig.extension }
