#sylius_admin_pictogram:
#    resource: |
#        alias: asdoria.pictogram
#        section: admin
#        templates: "@SyliusAdmin\\Crud"
#        except: ['show']
#        redirect: index
#        grid: sylius_admin_pictogram
#        permission: true
#        vars:
#           all:
#             templates:
#                form: '@AsdoriaSyliusPictogramPlugin/Admin/Pictogram/_form.html.twig'
#    type: sylius.resource
