#Asdoria\SyliusPictogramPlugin\Entity\PictogramImage:
#    properties:
#        path:
#            - NotBlank:
#                  groups: [ sylius ]
#                  message: 'asdoria.ui.image.path.not_blank'
