sylius_ui:
    events:
        sylius.admin.product.update.javascripts:
            blocks:
                asdoria_pictograms_javascripts:
                    template: "@AsdoriaSyliusPictogramPlugin/Admin/_javascripts.html.twig"
                    priority: 10
        sylius.admin.product.create.javascripts:
            blocks:
                asdoria_pictograms_javascripts:
                    template: "@AsdoriaSyliusPictogramPlugin/Admin/_javascripts.html.twig"
                    priority: 10
        sylius.admin.product.update.stylesheets:
            blocks:
                asdoria_pictograms_stylesheets:
                    template: "@AsdoriaSyliusPictogramPlugin/Admin/_stylesheets.html.twig"
                    priority: 10
        sylius.admin.product.create.stylesheets:
            blocks:
                asdoria_pictograms_stylesheets:
                    template: "@AsdoriaSyliusPictogramPlugin/Admin/_stylesheets.html.twig"
                    priority: 10

        asdoria.admin.pictogram.index.stylesheets:
            blocks:
                asdoria_pictograms_stylesheets:
                    template: "@AsdoriaSyliusPictogramPlugin/Admin/_stylesheets.html.twig"
                    priority: 10
        asdoria.admin.pictogram.index.javascripts:
            blocks:
                asdoria_pictograms_javascripts:
                    template: "@AsdoriaSyliusPictogramPlugin/Admin/_javascripts.html.twig"
                    priority: 10

        asdoria.admin.pictogram_group.index.javascripts:
            blocks:
                asdoria_pictogram_groups_javascripts:
                    template: "@AsdoriaSyliusPictogramPlugin/Admin/_javascripts.html.twig"
                    priority: 10

        sylius.shop.product.show.content:
            blocks:
                asdoria_pictograms:
                    template: "@AsdoriaSyliusPictogramPlugin/Shop/Product/show/_groupsPicto.html.twig"
                    priority: 25
