Asdoria\SyliusPictogramPlugin\Entity\PictogramTranslation:
    exclusion_policy: ALL
    xml_root_name: pictogram_translation
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed, Autocomplete]
        name:
            expose: true
            type: string
            groups: [Default, Detailed, Autocomplete]
